# Generated by Django 6.0.1 on 2026-01-12 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem1',
            old_name='prices',
            new_name='price',
        ),
    ]
