# Generated by Django 5.1.7 on 2026-01-12 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem1_id_alter_orderitem2_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orderitem1',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='orderitem2',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', 'created_at'], name='orders_orde_user_id_37fed6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem1',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_93b637_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem2',
            index=models.Index(fields=['order', 'created_at'], name='orders_orde_order_i_c4a150_idx'),
        ),
    ]
