# Generated by Django 5.1.7 on 2026-01-12 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_created_at_alter_orderitem1_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem2',
            name='q',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
