# Generated by Django 5.1.7 on 2026-01-12 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderitem2_q'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem2',
            name='q',
        ),
    ]
